spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.id} # gmtp Account Id
    password: ${email.pwd} # gmtp Account Password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        debug: false # email sending process log
  config:
    import: classpath:secret.yml # gmtp Account


logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
